### ISSUE TITLE
Behavior with "igfxfw=1"

### ISSUE THREAD

**Issue by danieldegrasse** [lvs1974/IntelGraphicsFixup#5]
I was wondering about the boot argument "igfxfw=1" and its behavior. I know that high sierra does attempt to load firmware onto graphics devices (Hash data from ME never returned, and disablegfxfirmware boot arg), but I was wondering what firmware this is and if igfxfw=1 loads different microcode. Specifically, what are the underlying differences between the default behavior of the extension, where -disablegfxfirmware is no longer required, and the behavior of the extension when igfxfw=1 is provided as a boot arg. I noticed when I provide igfxfw=1 that brightness control breaks, although I'm not sure why.

**Comment by vit9696** [comment]
Unfortunately IGScheduler4, which igfxfw=1 relies on, is half-implemented by Apple. IntelGraphicsFixup tries to fix it to some level, but without a full success. That's why the argument is needed to enable the firmware.

It loads the GuC firmware from [here](https://01.org/linuxgraphics/downloads/firmware), while Apple usually has its own binaries.
